# Generated by Django 3.2.4 on 2021-06-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioGolf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fullImageName',
            field=models.TextField(null=True),
        ),
    ]
