# Generated by Django 3.2.4 on 2021-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioGolf', '0002_character_fullimagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='characterPrimaryColor',
            field=models.TextField(default='#ff0001'),
        ),
    ]
