# Generated by Django 3.2.4 on 2021-06-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marioGolf', '0003_character_characterprimarycolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.TextField(unique=True)),
                ('courseDescription', models.TextField(null=True)),
                ('courseGlyph', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holeNumber', models.PositiveSmallIntegerField()),
                ('par', models.PositiveSmallIntegerField()),
                ('distanceFromTee', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.course')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('startDate', models.DateTimeField(default='current_timestamp()')),
                ('endDate', models.DateTimeField(null=True)),
                ('numOfHoles', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='characterType',
        ),
        migrations.CreateModel(
            name='TournamentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overallScore', models.IntegerField()),
                ('placement', models.PositiveSmallIntegerField()),
                ('tournamentEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.tournamententry')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.hole')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentEntryHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotsTaken', models.PositiveSmallIntegerField()),
                ('puttsTaken', models.PositiveSmallIntegerField()),
                ('tournamentEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.tournamententry')),
                ('tournamentHole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.tournamenthole')),
            ],
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.character'),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.player'),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournamentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.tournamenttype'),
        ),
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterType', models.TextField(choices=[('SPEED', 'Speed'), ('POWER', 'Power'), ('CONTROL', 'Control'), ('SPIN', 'Spin'), ('ALL-ROUND', 'All-Round')])),
                ('characterPower', models.PositiveIntegerField()),
                ('character2StarPower', models.PositiveIntegerField(null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.character')),
            ],
        ),
    ]
