# Generated by Django 3.2.4 on 2021-06-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marioGolf', '0005_tournamententryhole_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplacement',
            name='tournamentEntry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marioGolf.tournamententry'),
        ),
    ]
