# Generated by Django 3.2.4 on 2021-06-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marioGolf', '0008_remove_tournamententryhole_puttstaken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentPlacement',
        ),
    ]
