# Generated by Django 3.1.7 on 2021-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0003_auto_20210325_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelaner',
            name='championSelectOrder',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
