# Generated by Django 3.1.7 on 2021-03-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0005_auto_20210325_1752'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamelaner',
            unique_together={('game', 'lane', 'blueTeam')},
        ),
    ]
