# Generated by Django 3.1.7 on 2021-04-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0006_auto_20210325_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLanerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('largestKillingSpree', models.PositiveIntegerField()),
                ('largestMultiKill', models.PositiveIntegerField()),
                ('doubleKills', models.PositiveIntegerField()),
                ('tripleKills', models.PositiveIntegerField()),
                ('quadraKills', models.PositiveIntegerField()),
                ('pentaKills', models.PositiveIntegerField()),
                ('totalDamageDealtToChampions', models.PositiveBigIntegerField()),
                ('visionScore', models.PositiveIntegerField()),
                ('crowdControlScore', models.PositiveIntegerField()),
                ('totalDamageTaken', models.PositiveBigIntegerField()),
                ('goldEarned', models.PositiveBigIntegerField()),
                ('turretKills', models.PositiveIntegerField()),
                ('inhibitorKills', models.PositiveIntegerField()),
                ('laneMinionsKilled', models.PositiveIntegerField()),
                ('neutralMinionsKilled', models.PositiveIntegerField()),
                ('teamJungleMinionsKilled', models.PositiveIntegerField()),
                ('enemyJungleMinionsKilled', models.PositiveIntegerField()),
                ('controlWardsPurchased', models.PositiveIntegerField()),
                ('firstBlood', models.BooleanField()),
                ('firstTower', models.BooleanField()),
                ('csRateFirstTen', models.FloatField()),
                ('csRateSecondTen', models.FloatField()),
                ('gameLaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenMans.gamelaner')),
            ],
        ),
    ]
