# Generated by Django 3.1.7 on 2021-04-07 14:49

from django.db import migrations, models
from datetime import timedelta
class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0007_gamelanerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameDuration',
            field=models.DurationField(default=timedelta()),
        ),
    ]
