# Generated by Django 3.1.7 on 2021-04-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0009_game_gameriotid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelanerstats',
            name='gameLaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenMans.gamelaner', unique=True),
        ),
    ]
