# Generated by Django 3.1.7 on 2021-04-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0010_auto_20210407_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelanerstats',
            name='gameLaner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenMans.gamelaner'),
        ),
    ]
