# Generated by Django 3.1.7 on 2021-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0013_auto_20210410_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='riotName',
            field=models.TextField(null=True, unique=True),
        ),
    ]
