# Generated by Django 3.2.5 on 2021-07-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0018_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='leaderboardURLName',
            field=models.TextField(default=''),
        ),
    ]
