# Generated by Django 3.2.5 on 2021-07-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0019_leaderboard_leaderboardurlname'),
    ]

    operations = [
        migrations.RunSQL([
            "ALTER DATABASE tenmansstatistics CHARACTER SET = utf8mb4 COLLATE utf8mb4_unicode_ci",
            "ALTER TABLE tenmans_leaderboard CONVERT TO CHARACTER SET utf8mb4 COLLATE UTF8MB4_UNICODE_CI",
            "ALTER TABLE tenmans_leaderboard CHANGE leaderboardEmoji leaderboardEmoji LONGTEXT CHARACTER SET utf8mb4 COLLATE UTF8MB4_UNICODE_CI"
        ]
        )
    ]
