# Generated by Django 3.2.6 on 2021-11-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0023_alter_game_gamedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonNumber', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.RunSQL([
            "INSERT INTO tenmans_season VALUES (1, 1), (2, 2), (3, 3)",
        ]
        )

    ]
