# Generated by Django 3.2.6 on 2021-11-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0024_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenMans.season'),
        ),
        migrations.RunSQL([
            "UPDATE tenMans_game SET season_id = 2 WHERE gameNumber > 23",
        ]
        )
    ]
