# Generated by Django 3.2.9 on 2021-11-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0025_game_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameEndedInEarlySurrender',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='gameEndedInSurrender',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='baronKills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='dragonKills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='goldSpent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='killedNexus',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='largestCriticalStrike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='longestTimeSpentLiving',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='numberOfFlashes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='objectivesStolen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='timePlayed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelanerstats',
            name='totalTimeSpentDead',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamelanerstats',
            name='goldEarned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
