# Generated by Django 3.2.4 on 2021-06-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterName', models.TextField(unique=True)),
                ('characterType', models.TextField(choices=[('SPEED', 'Speed'), ('POWER', 'Power'), ('CONTROL', 'Control'), ('SPIN', 'Spin'), ('ALL-ROUND', 'All-Round')])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.TextField(unique=True)),
            ],
        ),
    ]
