# Generated by Django 3.1.7 on 2021-03-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championName', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameNumber', models.PositiveIntegerField(unique=True)),
                ('gameBlueWins', models.BooleanField()),
                ('gameRandomTeams', models.BooleanField()),
                ('gameMemeStatus', models.BooleanField(default=0)),
                ('gameDate', models.DateTimeField(default='current_timestamp()')),
            ],
            options={
                'verbose_name_plural': 'games',
                'ordering': ['gameNumber'],
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laneName', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.TextField(unique=True)),
            ],
        ),
    ]
