# Generated by Django 3.1.7 on 2021-03-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueTeam', models.BooleanField(default=1)),
                ('draftOrder', models.PositiveIntegerField()),
                ('championSelectOrder', models.PositiveIntegerField()),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenMans.champion')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenMans.game')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenMans.lane')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenMans.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameBans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenMans.champion')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenMans.game')),
                ('targetPlayer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenMans.player')),
            ],
        ),
    ]
