# Generated by Django 3.1.7 on 2021-04-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0008_game_gameduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameRiotID',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
