# Generated by Django 3.1.7 on 2021-04-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0016_remove_champion_championimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamelaner',
            unique_together={('player', 'game'), ('game', 'lane', 'blueTeam')},
        ),
    ]
