# Generated by Django 3.2.9 on 2021-11-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0026_auto_20211108_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelanerstats',
            name='goldEarned',
            field=models.PositiveBigIntegerField(),
        ),
    ]
