# Generated by Django 3.1.7 on 2021-04-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenMans', '0015_champion_championimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='championImage',
        ),
    ]
