# Generated by Django 3.2.4 on 2021-06-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marioGolf', '0007_remove_hole_distancefromtee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamententryhole',
            name='puttsTaken',
        ),
    ]
